# Workflow derived from https://github.com/marketplace/actions/github-action-for-rmarkdown
# cron tip from https://www.lagerdata.com/articles/setting-up-a-cron-job-with-github-actions
on:
  push:
    branches: [main, master]
  schedule:
    - cron:  "46 7 * * *" # Build project at 6:46 UTC each morning

name: render_document

jobs:
  render_document:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Render document
        uses: lc5415/rmarkdown-action@v1
        with:
          input_file: corona_vaccination_de_regional.Rmd
	  output_format: html_document